# Generated by Django 4.0.3 on 2022-05-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_options_remove_profile_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default/default_avatar.jpg', upload_to='user/%y/%m/%d'),
            preserve_default=False,
        ),
    ]
