# Generated by Django 4.0.3 on 2022-04-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogSite', '0006_comment_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
