# Generated by Django 4.0.3 on 2022-04-10 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogSite', '0011_emotion_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotions', to='blogSite.post'),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion', to=settings.AUTH_USER_MODEL),
        ),
    ]
