# Generated by Django 4.0.4 on 2022-05-15 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogSite', '0012_alter_emotion_post_alter_emotion_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emotion',
        ),
    ]
