# Generated by Django 4.0.3 on 2022-05-16 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogSite', '0013_delete_emotion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
