# Generated by Django 4.0.3 on 2022-05-16 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogSite', '0014_delete_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='from_user',
            new_name='user',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('body', models.CharField(max_length=250)),
                ('edited', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogSite.post')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['update', 'create'],
            },
        ),
    ]
