# Generated by Django 4.0.4 on 2022-05-15 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='from_user',
            new_name='user',
        ),
    ]
